#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
polybar example &

# xfce settings
xfsettingsd &

 Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 2
bspc config top_padding 16
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a thunar desktop='^1' state=floating follow=on

